version: "3.8"
services:
  aqm:
    image: "[username]/[repository]:[version]"
    ports:
      - "4000-4001:3000"
    restart: always
    environment:
      - ACCOUNT_NAME=[ACCOUNT_NAME]
      - ACCOUNT_KEY=[ACCOUNT_KEY]
      - HIGH_PRIORITY_VISIBILITY_TIMEOUT=30
      - MIDDLE_PRIORITY_VISIBILITY_TIMEOUT=30
      - LOW_PRIORITY_VISIBILITY_TIMEOUT=30
      - CRON_INTERVAL=1000